on: push
name: build
jobs:
  build-linux:
    name: build on Ubuntu
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - run: bin/build-linux-x86-64.sh
      - uses: actions/upload-artifact@v1
        with:
          name: linux-x86-64
          path: artifacts/linux-x86-64

  deploy:
    name: deploy
    needs: [build-linux]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v1
        with:
          name: linux-x86-64
          path: artifacts/linux-x86-64
      - run: bin/deploy.sh
        if: >-
          startsWith(github.ref, 'refs/tags/v')
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_KEY_PASSPHRASE: ${{ secrets.DEPLOY_KEY_PASSPHRASE }}
